services:
  - type: web
    name: elitepro-template
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://elitepro-template-1.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: SESSION_SECURE_COOKIE
        value: true
